In [4]:
############## 什么是 Numpy 和 Numpy array ##############  
import numpy as np

In [9]:
# 创建数组示例
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [4]:
# Numpy array 相较原始 list 速度更快  
L = range(1000)
%timeit [i**2 for i in L]
print("------------------------------------")
a = np.arange(1000)
%timeit a**2

1000 loops, best of 3: 325 µs per loop
--------------------


The slowest run took 9.00 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.89 µs per loop


In [7]:
# 参考文档与帮助
# 查看 np.array 函数文档
np.array? 
# 查看如何 create array
np.lookfor('create array')
# 查看 Numpy 中以 con 开头的函数
np.con*?

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [10]:
############## 创建 Numpy 数组 ##############  
import numpy as np

In [16]:
# 使用构造函数创建 1 维数组 , np.array 函数中传入 Python List
a = np.array([0, 1, 2, 3])
print(a.ndim)  # 数组维度
print(a.shape)  # 数组形状
print(len(a))  # 返回数组第一维度的元素个数
print("------------------------------------")

# 使用构造函数创建 2 维数组 , np.array 函数中传入 Python List 的 List
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a.ndim)
print(a.shape)
print(len(a))
print("------------------------------------")

# 使用构造函数创建 3 维数组 , 这里仅仅是说明如何看 List 的 List 确定是几维数组
a = np.array([[[1], [2]], [[3], [4]]])
print(a.ndim)
print(a.shape)
print(a)

1
(4,)
4
------------------------------------
2
(2, 3)
2
------------------------------------
3
(2, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]]


In [3]:
# 使用特殊函数创建 np.arange , 生成 int
a = np.arange(10) # 创建 1 维 10 个元素的数组从 0 ~ 9
print(a)
a = np.arange(1, 9, 2)  # 创建 1 维数组 , 开始元素是 start = 1 end = 9 (exclusive) step = 2
print(a)
print("------------------------------------")
# 使用特殊函数创建 np.linespace , 生成 float
a = np.linspace(0, 1, 5)  # 0 ~ 1 区间均匀产生 7 个数 1 , 1 包括在内
print(a)
a = np.linspace(0, 1, 5, endpoint=False)  # 0 ~ 1 区间均匀产生 6 个数 , 1 不包括在内
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
------------------------------------
[ 0.    0.25  0.5   0.75  1.  ]
[ 0.   0.2  0.4  0.6  0.8]


In [5]:
# 使用 Matlab 风格函数创建 np.ones
a = np.ones((3, 3))  # 生成 3×3 全 1 二维数组 , 默认 float 类型 , 可以修改 dtype 参数设置
print(a)
print("------------------------------------")
a = np.zeros((3, 3))  # 生成 3×3 全 0 二维数组 , 默认 float 类型 , 可以修改 dtype 参数设置
print(a)
print("------------------------------------")
a = np.eye(3)  # 生成 3×3 单位阵（二维数组） , 默认 float 类型 , 可以修改 dtype 参数设置
print(a)
print("------------------------------------")
a = np.diag(np.arange(4))  # 生成主对角线元素为 0 , 1 , 2 其余元素为 0 的二维数组
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
------------------------------------
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
------------------------------------
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
------------------------------------
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [29]:
# 使用随机数函数创建 
a = np.random.rand(4) # 生成 4 个 [0, 1] 均匀分布随机数组成的一维数组
print(a)
print("------------------------------------")
a = np.random.randn(4)  # 生成 4 个高斯分布随机数组成的一维数组
print(a)
print("------------------------------------")
a = np.random.seed(100)  # 随机种子

[ 0.13665982  0.9942047   0.68353681  0.15100747]
------------------------------------
[ 0.02524517 -1.50990928  0.34709143 -0.5675784 ]
------------------------------------
