# 目录
* 什么是 Numpy 和 Numpy array
* 创建 Numpy 数组
* 索引和切片
* 拷贝和视图
* 高级索引技巧

## 什么是 Numpy 和 Numpy array


In [1]:
import numpy as np

In [3]:
# 创建数组示例
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [4]:
# Numpy array 相较原始 list 速度更快  
L = range(1000)
%timeit [i**2 for i in L]
print("------------------------------------")
a = np.arange(1000)
%timeit a**2

1000 loops, best of 3: 421 µs per loop
------------------------------------


The slowest run took 64.23 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 1.96 µs per loop


In [6]:
# 参考文档与帮助
# 查看 np.array 函数文档
np.array?
# 查看如何 create array
np.lookfor('create array')
# 查看 Numpy 中以 con 开头的函数
np.con*?

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

## 创建 Numpy 数组

In [2]:
# 使用构造函数创建 1 维数组 , np.array 函数中传入 Python List
a = np.array([0, 1, 2, 3])
print(a.ndim)  # 数组维度
print(a.shape) # 数组形状
print(len(a))  # 返回数组第一维度的元素个数
print("------------------------------------")

# 使用构造函数创建 2 维数组 , np.array 函数中闯入 Python List 的 List
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a.ndim)
print(a.shape)
print(len(a))
print("------------------------------------")

# 使用构造函数创建 3 维数组 , 这里仅仅是说明如何看 List 的 List 确定是几维数组
a = np.array([[[1], [2]], [[3], [4]]])
print(a.ndim)
print(a.shape)
print(a)

1
(4,)
4
------------------------------------
2
(2, 3)
2
------------------------------------
3
(2, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]]


In [8]:
# 使用特殊函数创建 np.arange , 生成 int
a = np.arange(10) # 创建 1 维 10 个元素的数组从 0 ~ 9
print(a)
a = np.arange(1, 9, 2)  # 创建 1 维数组 , 开始元素是 start = 1 end = 9 (exclusive) step = 2
print(a)
print("------------------------------------")
# 使用特殊函数创建 np.linespace , 生成 float
a = np.linspace(0, 1, 5)  # 0 ~ 1 区间均匀产生 7 个数 1 , 1 包括在内
print(a)
a = np.linspace(0, 1, 5, endpoint=False)  # 0 ~ 1 区间均匀产生 6 个数 , 1 不包括在内
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
------------------------------------
[ 0.    0.25  0.5   0.75  1.  ]
[ 0.   0.2  0.4  0.6  0.8]


In [9]:
# 使用 Matlab 风格函数创建 np.ones
a = np.ones((3, 3))  # 生成 3×3 全 1 二维数组 , 默认 float 类型 , 可以修改 dtype 参数设置
print(a)
print("------------------------------------")
a = np.zeros((3, 3))  # 生成 3×3 全 0 二维数组 , 默认 float 类型 , 可以修改 dtype 参数设置
print(a)
print("------------------------------------")
a = np.eye(3)  # 生成 3×3 单位阵（二维数组） , 默认 float 类型 , 可以修改 dtype 参数设置
print(a)
print("------------------------------------")
a = np.diag(np.arange(4))  # 生成主对角线元素为 0 , 1 , 2 其余元素为 0 的二维数组
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
------------------------------------
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
------------------------------------
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
------------------------------------
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [10]:
# 使用随机数函数创建 
a = np.random.rand(4) # 生成 4 个 [0, 1] 均匀分布随机数组成的一维数组
print(a)
print("------------------------------------")
a = np.random.randn(4)  # 生成 4 个高斯分布随机数组成的一维数组
print(a)
print("------------------------------------")
a = np.random.seed(100)  # 随机种子

[ 0.46676674  0.14691211  0.2595242   0.09534165]
------------------------------------
[ 1.40338122  0.58489055  0.76655198 -0.74145475]
------------------------------------


## 索引和切片

In [11]:
# List 方式索引 Numpy 数组对象
# 一维
a = np.arange(10)
print(a)
print(a[0], a[2], a[-1], a[-2])  # 下标从 0 开始
print("------------------------------------")
# 二维
a = np.diag(np.arange(3))
print(a)
print(a[1, 1])  # [行索引, 列索引] 下标从 0 开始
print(a[2, 2])
print(a[0])  # 返回第 1 行   
print(a[:, 2])  # 返回第 3 列 , : 代表全部

[0 1 2 3 4 5 6 7 8 9]
0 2 9 8
------------------------------------
[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
2
[0 0 0]
[0 0 2]


In [12]:
# List 方式切片 Numpy 数组对象
# 一维
a = np.arange(10)
print(a)
print(a[2:9:3])  # [start:exclusive:step]
print(a[2:8:3])  # start 默认值 0
                 # exclusive 默认值 last element index + 1 （也就是 end 为最后一个元素 include）
                 # step 1
print(a[:4:])  # 省略 start = 0
               # 省略 step = 1
print(a[::-2])  # step 负数 先逆序再|step| 
print("------------------------------------")
# 二维
a = np.arange(36).reshape((6, 6))
print(a)
print(a[4::, 4::])
print(a[:, 2])  # : 代表全部
print(a[2::2, ::2])

[0 1 2 3 4 5 6 7 8 9]
[2 5 8]
[2 5]
[0 1 2 3]
[9 7 5 3 1]
------------------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[28 29]
 [34 35]]
[ 2  8 14 20 26 32]
[[12 14 16]
 [24 26 28]]


In [13]:
# 索引、切片与赋值
# 索引赋值
a = np.arange(10)
a[1] = 10
print(a)
print("------------------------------------")
# 切片赋值
a = np.arange(10)
a[5:] = 10 # 注意有一个
print(a)

[ 0 10  2  3  4  5  6  7  8  9]
------------------------------------
[ 0  1  2  3  4 10 10 10 10 10]


## 拷贝和视图

In [14]:
a = np.arange(10)
# 切片 默认浅拷贝 可以调整为深拷贝
print(np.may_share_memory(a, a[::2]))  # 浅拷贝
print(np.may_share_memory(a, a[::2].copy))  # 深拷贝
# 索引 默认深拷贝
print(np.may_share_memory(a, a[0]))
print("------------------------------------")
print(np.may_share_memory(a, a[a % 2 == 0]))
print(a[a % 2 == 0].shape)
print("------------------------------------")
print(np.may_share_memory(a, a[[1, 1, 2, 2, 3, 3]]))
print(a[[1, 1, 2, 2, 3, 3]].shape)
print("------------------------------------")

True
False
False
------------------------------------
False
(5,)
------------------------------------
False
(6,)
------------------------------------


## 高级索引技巧

In [ ]:
a = np.arange(10)
print(np.may_share_memory(a, a[a % 2 == 0]))
print(a[a % 2 == 0].shape)
print("------------------------------------")
print(np.may_share_memory(a, a[[1, 1, 2, 2, 3, 3]]))
print(a[[1, 1, 2, 2, 3, 3]].shape)
print("------------------------------------")
a = np.arange(36).reshape((6, 6))


## 数组组合

In [ ]:
a = np.arange(9).reshape(3,3)
b = 2 * a
print("------------------ cbind() ----------------- ")
print(np.column_stack((a, b)))
print("------------------ rbind() ----------------- ")
print(np.row_stack((a, b)))

# And So On